# Generated by Django 5.2 on 2025-07-21 15:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardLayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="My Dashboard", max_length=200)),
                (
                    "layout_type",
                    models.CharField(
                        choices=[
                            ("grid", "Grid Layout"),
                            ("list", "List Layout"),
                            ("cards", "Card Layout"),
                            ("custom", "Custom Layout"),
                        ],
                        default="grid",
                        max_length=20,
                    ),
                ),
                ("columns", models.PositiveIntegerField(default=3)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light"),
                            ("dark", "Dark"),
                            ("auto", "Auto"),
                        ],
                        default="light",
                        max_length=20,
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(
                        default=dict, help_text="Widget positions and configurations"
                    ),
                ),
                (
                    "auto_refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Auto refresh interval in seconds"
                    ),
                ),
                ("show_animations", models.BooleanField(default=True)),
                ("compact_mode", models.BooleanField(default=False)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dashboard Layout",
                "verbose_name_plural": "Dashboard Layouts",
                "db_table": "dashboard_layout",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("position_x", models.PositiveIntegerField(default=0)),
                ("position_y", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=1)),
                ("height", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(blank=True, max_length=200)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Widget-specific configuration"
                    ),
                ),
                ("data_source", models.CharField(blank=True, max_length=200)),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=300, help_text="Refresh interval in seconds"
                    ),
                ),
                ("is_visible", models.BooleanField(default=True)),
                ("show_header", models.BooleanField(default=True)),
                ("show_border", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("cached_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "User Widget",
                "verbose_name_plural": "User Widgets",
                "db_table": "dashboard_user_widget",
                "ordering": ["display_order", "position_y", "position_x"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("portfolio_summary", "Portfolio Summary"),
                            ("watchlist", "Stock Watchlist"),
                            ("recent_signals", "Recent Trading Signals"),
                            ("market_overview", "Market Overview"),
                            ("performance_chart", "Performance Chart"),
                            ("top_gainers", "Top Gainers"),
                            ("top_losers", "Top Losers"),
                            ("news_feed", "News Feed"),
                            ("economic_calendar", "Economic Calendar"),
                            ("quick_actions", "Quick Actions"),
                            ("notifications", "Notifications"),
                            ("system_status", "System Status"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_size",
                    models.CharField(
                        choices=[
                            ("small", "Small (1x1)"),
                            ("medium", "Medium (2x1)"),
                            ("large", "Large (2x2)"),
                            ("wide", "Wide (3x1)"),
                            ("tall", "Tall (1x2)"),
                            ("extra_large", "Extra Large (3x2)"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_resizable", models.BooleanField(default=True)),
                ("is_moveable", models.BooleanField(default=True)),
                ("requires_data_source", models.BooleanField(default=False)),
                (
                    "config_schema",
                    models.JSONField(
                        default=dict, help_text="JSON schema for widget configuration"
                    ),
                ),
                (
                    "default_config",
                    models.JSONField(
                        default=dict, help_text="Default configuration values"
                    ),
                ),
                (
                    "min_subscription_level",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Professional"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("version", models.CharField(default="1.0.0", max_length=20)),
            ],
            options={
                "verbose_name": "Widget",
                "verbose_name_plural": "Widgets",
                "db_table": "dashboard_widget",
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DashboardAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("success", "Success"),
                            ("market", "Market Alert"),
                            ("system", "System Alert"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_dismissible", models.BooleanField(default=True)),
                (
                    "auto_dismiss_after",
                    models.PositiveIntegerField(
                        blank=True, help_text="Auto dismiss after X seconds", null=True
                    ),
                ),
                ("show_on_dashboard", models.BooleanField(default=True)),
                ("show_as_notification", models.BooleanField(default=False)),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("source", models.CharField(default="system", max_length=100)),
                ("action_url", models.URLField(blank=True)),
                ("action_text", models.CharField(blank=True, max_length=100)),
                (
                    "related_stock",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_alerts",
                        to="core.stocksymbol",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Alert",
                "verbose_name_plural": "Dashboard Alerts",
                "db_table": "dashboard_alert",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
