# Generated by Django 5.2 on 2025-07-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardalert",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific user (if null, alert is global)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboardlayout",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_layout",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwidget",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboard_widgets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userwidget",
            name="widget",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_instances",
                to="dashboard.widget",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardalert",
            index=models.Index(
                fields=["user", "is_dismissed", "valid_from"],
                name="dashboard_a_user_id_b0a518_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="dashboardalert",
            index=models.Index(
                fields=["alert_type", "level"], name="dashboard_a_alert_t_17cbfe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userwidget",
            unique_together={("user", "widget", "position_x", "position_y")},
        ),
    ]
