services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gpw_advisor_db
      POSTGRES_USER: gpw_user
      POSTGRES_PASSWORD: gpw_password
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gpw_user -d gpw_advisor_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application (Production)
  web:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped
    volumes:
      - static_files:/app/staticfiles
      - media_files:/app/media
      - log_files:/app/logs
    ports:
      - "${WEB_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker for background tasks
  celery_worker:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped
    command: celery -A gpw_advisor worker --loglevel=info
    volumes:
      - log_files:/app/logs
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Beat for scheduled tasks
  celery_beat:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    restart: unless-stopped
    command: celery -A gpw_advisor beat --loglevel=info
    volumes:
      - log_files:/app/logs
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  static_files:
  media_files:
  log_files:
