services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: gpw_advisor_db
      POSTGRES_USER: gpw_user
      POSTGRES_PASSWORD: gpw_password
    ports:
      - "${DB_PORT:-5433}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gpw_user -d gpw_advisor_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django Web Application (Development)
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./staticfiles:/app/staticfiles
    ports:
      - "${WEB_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Worker (Development)
  celery:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A gpw_advisor worker --loglevel=debug --concurrency=1
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Celery Beat (Development)
  celery-beat:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A gpw_advisor beat --loglevel=debug
    volumes:
      - .:/app
      - ./logs:/app/logs
    environment:
      - DEBUG=True
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=gpw_user
      - DATABASE_PASSWORD=gpw_password
      - DATABASE_NAME=gpw_advisor_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
