# Generated by Django 5.2 on 2025-07-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # This migration marks the existing news tables as managed by Django
        # Tables already exist from previous setup, so no CreateModel operations needed
    ]
