# Generated by Django 5.2 on 2025-07-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_add_llm_and_market_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticlemodel",
            name="url",
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
