# Generated by Django 5.2 on 2025-07-22 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_alter_technicalindicator_options_and_more"),
        ("core", "0005_scrapingschedule_scrapingexecution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prediction_type",
                    models.CharField(
                        choices=[
                            ("intraday_price", "Intraday Price"),
                            ("price_direction", "Price Direction"),
                            ("anomaly_detection", "Anomaly Detection"),
                            ("volume_prediction", "Volume Prediction"),
                        ],
                        default="intraday_price",
                        max_length=30,
                    ),
                ),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "predicted_change_percent",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=8, null=True
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Model confidence score (0.0 - 1.0)"),
                ),
                (
                    "prediction_horizon_hours",
                    models.IntegerField(
                        default=4, help_text="Prediction horizon in hours"
                    ),
                ),
                (
                    "actual_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Actual price outcome for accuracy tracking",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "accuracy_score",
                    models.FloatField(
                        blank=True,
                        help_text="Calculated accuracy score (0.0 - 1.0)",
                        null=True,
                    ),
                ),
                (
                    "user_feedback",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="User feedback for model improvement",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        default="v1.0", help_text="ML model version used", max_length=20
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions",
                        to="core.stocksymbol",
                    ),
                ),
                (
                    "trading_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_predictions",
                        to="core.tradingsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "ML Prediction Result",
                "verbose_name_plural": "ML Prediction Results",
                "db_table": "analysis_prediction_result",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
