# Generated by Django 5.2 on 2025-08-10 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_predictionresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeWeightConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "trading_style",
                    models.CharField(
                        choices=[
                            ("intraday", "Intraday Trading"),
                            ("swing", "Swing Trading"),
                            ("position", "Position Trading"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "half_life_minutes",
                    models.IntegerField(
                        default=120,
                        help_text="Time in minutes for news impact to decay by 50%",
                    ),
                ),
                (
                    "last_15min_weight",
                    models.FloatField(
                        default=0.4,
                        help_text="Weight for news from last 15 minutes",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "last_1hour_weight",
                    models.FloatField(
                        default=0.3,
                        help_text="Weight for news from last 1 hour",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "last_4hour_weight",
                    models.FloatField(
                        default=0.2,
                        help_text="Weight for news from last 4 hours",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "today_weight",
                    models.FloatField(
                        default=0.1,
                        help_text="Weight for older news from today",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "breaking_news_multiplier",
                    models.FloatField(
                        default=2.0,
                        help_text="Multiplier for high-impact breaking news",
                    ),
                ),
                (
                    "market_hours_multiplier",
                    models.FloatField(
                        default=1.5,
                        help_text="Multiplier for news published during market hours",
                    ),
                ),
                (
                    "pre_market_multiplier",
                    models.FloatField(
                        default=1.2,
                        help_text="Multiplier for news published in pre-market hours",
                    ),
                ),
                (
                    "min_impact_threshold",
                    models.FloatField(
                        default=0.05,
                        help_text="Minimum impact score to consider news relevant",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Time Weight Configuration",
                "verbose_name_plural": "Time Weight Configurations",
                "db_table": "analysis_time_weight_configs",
            },
        ),
    ]
