blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/YOUR_USERNAME/gpw-trading-advisor/discussions
    about: Ask questions, share ideas, and discuss with the community

  - name: 📖 Documentation
    url: https://github.com/YOUR_USERNAME/gpw-trading-advisor/wiki
    about: Check our documentation and guides

  - name: 🚨 Security Issues
    url: mailto:security@yourdomain.com
    about: Please report security vulnerabilities via email
