# Generated by Django 5.2 on 2025-07-21 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockSymbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "symbol",
                    models.CharField(
                        db_index=True,
                        help_text="Stock symbol (e.g., PKN, CDR, PKO)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Full company name", max_length=200),
                ),
                (
                    "sector",
                    models.CharField(
                        blank=True, help_text="Industry sector", max_length=100
                    ),
                ),
                (
                    "is_monitored",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this stock is actively monitored",
                    ),
                ),
                (
                    "stooq_url",
                    models.URLField(
                        blank=True, help_text="URL for scraping data from stooq.pl"
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Symbol",
                "verbose_name_plural": "Stock Symbols",
                "db_table": "core_stock_symbol",
                "ordering": ["symbol"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TradingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(db_index=True, unique=True)),
                ("is_trading_day", models.BooleanField(default=True)),
                ("market_open_time", models.TimeField(default=datetime.time(9, 0))),
                ("market_close_time", models.TimeField(default=datetime.time(17, 30))),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Trading Session",
                "verbose_name_plural": "Trading Sessions",
                "db_table": "core_trading_session",
                "ordering": ["-date"],
                "abstract": False,
            },
        ),
    ]
