# Generated by Django 5.2 on 2025-07-21 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_llm_and_market_models"),
        ("news", "0002_add_llm_and_market_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsclassification",
            name="article",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_classification",
                to="news.newsarticlemodel",
            ),
        ),
        migrations.AddField(
            model_name="newsclassification",
            name="detected_industries",
            field=models.ManyToManyField(
                blank=True, related_name="news_classifications", to="core.industry"
            ),
        ),
        migrations.AddField(
            model_name="newsclassification",
            name="llm_provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classifications",
                to="core.llmprovider",
            ),
        ),
        migrations.AddField(
            model_name="newsclassification",
            name="primary_industry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_news_classifications",
                to="core.industry",
            ),
        ),
    ]
