# Generated by Django 5.2 on 2025-08-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_scrapingschedule_scrapingexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocksymbol",
            name="bankier_symbol",
            field=models.CharField(
                blank=True,
                help_text="Symbol used on bankier.pl (e.g., 11BIT, PKOBP)",
                max_length=20,
            ),
        ),
    ]
