# Generated by Django 5.2 on 2025-07-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_api_access_enabled_user_can_access_analytics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(
                blank=True, help_text="City of residence", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country of residence", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, help_text="Date of birth", null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="investment_goals",
            field=models.CharField(
                blank=True,
                choices=[
                    ("retirement", "Retirement Planning"),
                    ("income", "Income Generation"),
                    ("growth", "Capital Growth"),
                    ("speculation", "Speculation"),
                    ("hedging", "Risk Hedging"),
                ],
                help_text="Primary investment goals",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_markets",
            field=models.CharField(
                blank=True,
                choices=[
                    ("stocks", "Stocks Only"),
                    ("bonds", "Bonds Only"),
                    ("mixed", "Stocks & Bonds"),
                    ("crypto", "Cryptocurrency"),
                    ("commodities", "Commodities"),
                    ("all", "All Markets"),
                ],
                help_text="Preferred investment markets",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trading_experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner (0-1 years)"),
                    ("intermediate", "Intermediate (1-5 years)"),
                    ("advanced", "Advanced (5+ years)"),
                    ("professional", "Professional"),
                ],
                help_text="Trading experience level",
                max_length=20,
            ),
        ),
    ]
