# Generated by Django 5.2 on 2025-07-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapers", "0002_companycalendarevent_espireport_newsarticlemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycalendarevent",
            name="date_changes_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="companycalendarevent",
            name="last_date_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companycalendarevent",
            name="original_date",
            field=models.DateTimeField(
                blank=True, help_text="Original announced date", null=True
            ),
        ),
        migrations.CreateModel(
            name="EventDateChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_date", models.DateTimeField()),
                ("new_date", models.DateTimeField()),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("postponed", "Event Postponed"),
                            ("advanced", "Event Advanced"),
                            ("rescheduled", "Event Rescheduled"),
                            ("cancelled", "Event Cancelled"),
                            ("confirmed", "Date Confirmed"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "sentiment_impact",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                        ],
                        max_length=10,
                    ),
                ),
                ("change_reason", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_changes",
                        to="scrapers.companycalendarevent",
                    ),
                ),
            ],
            options={
                "db_table": "scrapers_event_date_changes",
                "ordering": ["-detected_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "detected_at"],
                        name="scrapers_ev_event_i_b0a1c8_idx",
                    ),
                    models.Index(
                        fields=["change_type"], name="scrapers_ev_change__2aee0d_idx"
                    ),
                    models.Index(
                        fields=["sentiment_impact"],
                        name="scrapers_ev_sentime_0cfb7b_idx",
                    ),
                ],
            },
        ),
    ]
