# Generated by Django 5.2 on 2025-07-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_scrapingschedule_scrapingexecution"),
        ("scrapers", "0003_add_date_change_tracking"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockdata",
            options={
                "ordering": ["-data_timestamp", "stock__symbol"],
                "verbose_name": "Stock Data",
                "verbose_name_plural": "Stock Data",
            },
        ),
        migrations.AlterUniqueTogether(
            name="stockdata",
            unique_together={("stock", "data_timestamp", "source")},
        ),
    ]
