# Generated by Django 5.2 on 2025-07-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0001_initial"),
        ("core", "0001_initial"),
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="performancemetrics",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performance_metrics",
                to="tracking.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="tracking.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="core.stocksymbol",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="portfolio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="tracking.portfolio",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="related_signal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="analysis.tradingsignal",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="stock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="core.stocksymbol",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="portfolio",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="performancemetrics",
            index=models.Index(
                fields=["portfolio", "date"], name="tracking_pe_portfol_ae6923_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="performancemetrics",
            unique_together={("portfolio", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("portfolio", "stock", "is_active")},
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["portfolio", "status"], name="tracking_tr_portfol_0c2aec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["stock", "opened_at"], name="tracking_tr_stock_i_9b5caa_idx"
            ),
        ),
    ]
