name: Dependency Updates & Security

on:
  schedule:
    # Run every Monday at 09:00 UTC
    - cron: '0 9 * * MON'
  workflow_dispatch: # Allow manual trigger

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Vulnerability Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit semgrep
        pip install -r requirements.txt
    
    - name: Run safety check for Python dependencies
      run: safety check --json --output safety-report.json
      continue-on-error: true
    
    - name: Run bandit security scan
      run: bandit -r . -f json -o bandit-report.json
      continue-on-error: true
    
    - name: Run semgrep security scan
      run: |
        semgrep --config=auto . --json --output=semgrep-report.json
      continue-on-error: true
    
    - name: Upload security reports
      uses: actions/upload-artifact@v3
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json
          semgrep-report.json

  docker-security:
    runs-on: ubuntu-latest
    name: Docker Image Security Scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build Docker image for scanning
      run: docker build -t gpw-advisor:scan .
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'gpw-advisor:scan'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  dependency-updates:
    runs-on: ubuntu-latest
    name: Check for Dependency Updates
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install pip-tools
      run: pip install pip-tools
    
    - name: Check for updates
      run: |
        pip-compile --upgrade requirements.txt
        if [ -f requirements-dev.txt ]; then
          pip-compile --upgrade requirements-dev.txt
        fi
    
    - name: Create Pull Request for updates
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update Python dependencies'
        title: 'chore: Update Python dependencies'
        body: |
          ## Dependency Updates
          
          This PR contains automated dependency updates.
          
          ### Changes
          - Updated Python packages to latest compatible versions
          - Security patches and bug fixes included
          
          ### Testing
          - [ ] All tests pass
          - [ ] Docker build succeeds  
          - [ ] Manual testing completed
          
          Auto-generated by GitHub Actions.
        branch: dependency-updates
        delete-branch: true
