# Generated by Django 5.2 on 2025-07-21 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notificationqueue",
            name="notification",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entry",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="template_used",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationqueue",
            index=models.Index(
                fields=["priority", "execute_at"], name="notificatio_priorit_e105b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationqueue",
            index=models.Index(
                fields=["is_processing", "execute_at"],
                name="notificatio_is_proc_190cfe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status"], name="notificatio_user_id_7088ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["status", "scheduled_at"], name="notificatio_status_a9c93f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="notificatio_notific_f2e0f7_idx",
            ),
        ),
    ]
